### ISSUE TITLE
ERROR: An extractor error has occurred. (caused by KeyError('meta',))

### ISSUE THREAD

**Issue by jainarya** [ytdl-org/youtube-dl#24316]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\USER\Downloads\youtube-dl>youtube-dl https://www.vlive.tv/video/166455?channelCode=B3A971 --username USERNAME --password PASSWORD --cookie cookies.txt -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.vlive.tv/video/166455?channelCode=B3A971', '--username', 'PRIVATE', '--password', 'PRIVATE', '--cookie', 'cookies.txt', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg git-2020-03-06-cfd9a65, ffprobe git-2020-03-06-cfd9a65
[debug] Proxy map: {}
[vlive] Downloading login cookies
[vlive] Logging in
[vlive] Downloading login info
[vlive] 166455: Downloading webpage
[vlive] 166455: Downloading live webpage
[vlive] 166455: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('meta',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\vlive.py", line 122, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\vlive.py", line 190, in _replay
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\naver.py", line 27, in _extract_video_info
KeyError: 'meta'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\vlive.py", line 122, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\vlive.py", line 190, in _replay
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\naver.py", line 27, in _extract_video_info
KeyError: 'meta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 543, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('meta',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I am currently trying to download paid CH+ content from VLIVE for which I have an account.
 "youtube-dl LINK --username USERNAME --password PASSWORD --cookie COOKIES.txt" used to work, but now this error occurs. I downloaded the cookie file using the Google Chrome "cookies.txt" extension. I have deleted all my browsing history and downloaded the cookie file again. I have reinstalled youtube-dl. I have tried different VLIVE+ links. My membership is still valid. Anyone able to shed light on this issue? Thank you very much in advance.

**Comment by dstftw** [comment]
You must provide account credentials for any work on this.

**Comment by jainarya** [comment]
I solved it. Hopefully this will help someone in the future.
I had exceeded the amount of devices for an account but it would still let me watch the video on my regular browser, but would not let youtube-dl access it (thus the "meta" error). I resetted it in my settings and it works perfectly again.
