### ISSUE TITLE
"--download-archive" option not tracking successful downloads of subtitles

### ISSUE THREAD

**Issue by etec-masterofsynapse** [ytdl-org/youtube-dl#25738]
- [X] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

When I am downloading a Vlive:Channel through the channel link and specify --download-archive in conjunction with --all-subs, I would expect that only videos where all subtitles were downloaded successfully get added to the txt to be ignored on later runs.

Vlive has this knack that depending on the speed of your internet connection you get WinError10060 URL timeouts, either on videos or on subtitles.

For videos, the error tracking works fine and the id gets excluded from the txt to be downloaded again on the next run. However with subtitles it doesnt work.
I have multiple examples where youtube-dl reported the WinError 10060 for a subtitle download but added the video id to the txt anyway.

Is this wanted behavior or a bug?
Thanks.

**Comment by dstftw** [comment]
This is expected behavior. Download archive is for video not subtitles as clearly stated in description.
