### ISSUE TITLE
http://dziga.meta.ua/ site support

### ISSUE THREAD

**Issue by ualaa1** [ytdl-org/youtube-dl#27220]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.11.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: http://dziga.meta.ua/2916375.video

## Description

This site is apparently closing on November 30th and I want to download some of the videos there before it shuts down.

**Comment by october262** [comment]
for this link -  http://dziga.meta.ua/2916375.video
just play the video and press F12  the debug menu shows
select network and then media click, on the single mp4 file and select copy link address
and just paste into youtube-dl to download the video.

**Comment by ualaa1** [comment]
That's weird. I tried that earlier and it didn't work, but now it does??
Thanks anyways
